name: 📦 Build and Release

on:
  push:
    paths:
      - lib/justifi/version.rb

jobs:
  build_and_release:
    strategy:
      matrix:
        include:
          - api_key: ${{ secrets.JUSTIFI_MACHINA_RUBYGEMS_API_KEY }}
            gem_host: https://rubygems.org
          - api_key: Bearer ${{ secrets.JUSTIFI_MACHINA_GITHUB_TOKEN }}
            gem_host: https://rubygems.pkg.github.com/${{ github.repository_owner }}

    name: 📦 Package and Release
    if: github.ref_type == 'branch' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 2.6
          rubygems: 3.2.32 # Required for GEM_HOST_API_KEY to work (delete if we use Ruby 3)

      # The `computed` value here is to solve for `-pre` style tags.
      # `raw_value` is what comes directly from the VERSION value, and
      # `computed` is what `Gem::Version` will output
      - name: Fetch Gem Version
        id: gem_version
        run: |
          ruby -r ./lib/justifi/version.rb -e '
            puts "::set-output name=raw_value::#{Justifi::VERSION}"
            puts "::set-output name=computed::#{Gem::Version.new(Justifi::VERSION)}"
          '

      # Combination of bundler's release steps and the steps here:
      #
      #   https://github.com/rickstaa/action-create-tag/blob/main/entrypoint.sh
      #
      - name: Tag Release
        id: git_tag
        if: matrix.gem_host == 'https://rubygems.org' # only do this step 1 time
        env:
          TAG: v${{ steps.gem_version.outputs.raw_value }}
          VERSION: ${{ steps.gem_version.outputs.raw_value }}
        run: |
          git config user.name "JustiFi Machina"
          git config user.email "justifi.machina@justifi.ai"
          git tag -a "${TAG}" -m "Version ${VERSION}" "${GITHUB_SHA}"
          git remote set-url origin "https://justifi-machina:${{ secrets.JUSTIFI_MACHINA_GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git push origin refs/tags/${TAG}

      - name: Build gem
        run: gem build justifi.gemspec

      - name: Publish gem to GitHub packages
        env:
          GEM_HOST_API_KEY: ${{ matrix.api_key }}
          RUBYGEMS_HOST: ${{ matrix.gem_host }}
          VERSION: ${{ steps.gem_version.outputs.computed }}
        run: |
          gem push --host ${RUBYGEMS_HOST} justifi-${VERSION}.gem
